### ISSUE TITLE
load error from tape

### ISSUE THREAD

**Issue by ErikApption** [nickbild/tflite_c64#3]
after hours of typing the program on my commodore 64, I saved it to tape but now it says load error

**Comment by nickbild** [comment]
Oh, no!  Sorry to hear that!  I'm surprised to hear that you actually spent all that time to type it in.

I copied the .bas file onto an SD card and loaded it into BASIC memory with an SD2IEC drive.  It works as expected, so I know that the program is OK.  I haven't used a tape drive for many years, but I think load errors are usually related to problems with the tape itself or a dirty/misaligned read head in the drive.

In any case, I don't think this is a problem with the BASIC program.  Re-open if you disagree.
